### ISSUE TITLE
appContext has not been initialized

### ISSUE THREAD

**Issue by SkyD666** [SkyD666/Rays-Android#23]
Process: com.skyd.rays
PID: 12220
UID: 10284
Frozen: false
Flags: 0x30e8be44
Package: com.skyd.rays v63 (2.2-beta03)
Foreground: No
Process-Runtime: 440
Build: Redmi/alioth/alioth:14/UKQ1.240116.001/V816.0.6.0.UNPCNXM:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ExceptionInInitializerError
	at com.skyd.rays.model.provider.StickerProvider.com.skyd.rays.config.StickerConfigKt.getSTICKER_DIR(SourceFile:80)
                                                 queryRoots
	at android.provider.DocumentsProvider.query(DocumentsProvider.java:915)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:298)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:110)
	at android.os.Binder.execTransactInternal(Binder.java:1346)
	at android.os.Binder.execTransact(Binder.java:1282)
Caused by: o7.x: lateinit property appContext has not been initialized
	at com.google.android.gms.internal.mlkit_vision_text_bundled_common.zbabx.com.skyd.rays.AppKt.getAppContext(SourceFile:8)
	at com.skyd.rays.config.StickerConfigKt.<clinit>(SourceFile:3)
	... 6 more

**Comment by SkyD666** [comment]
Solution: Use android.content.ContentProvider#getContext rather than appContext

**Comment by SkyD666** [comment]
Solution: Specify Context instead of using appContext in com.skyd.rays.config.StickerConfigKt
